### ISSUE TITLE
Make new features

### ISSUE THREAD

**Issue by vv0n** [moom825/xeno-rat#14]
1. Add exe to tray.
2. Notificate when (new) client connected. (turn/off)
3. Make gui resizable.
5. Dark theme. (cuntom theme)
6. Improve Builder gui. (arrange buttons, text, make it simple)
7. Add obfuscate check box on builder.
8. Add these options on builder: hidden, BSOD, Anti kill (blue screen when program killed), Usb spread
9. Add change file name textbox on builder. (If victim run rat file, allow it to rename(customizable on builder) the copied rat which is in appdata or temp.)
10. Process manager does not show all processes.
11. If I click + button on process manager, it is being closed everytime.
12. Make process manager show app icon.
13. Improve process manager and registry manager gui.
14. Make back up client.
15. If I don't enter version when I build, error occurs.
16. Add Language option. (don't really need)

**Comment by vv0n** [comment]
Must add these (accidently closed)

**Comment by moom825** [comment]
1. which exe, the server or the client
2. what do you think the notif should be, just a sound or a popup?
3. I didnt make it resizable for a reason, it was just annoying to deal with things when everything is resizable. it doesn't really affect the user experience and all the other windows are resizable
4/5. I'm bad with design, theres a reason it doesnt look spectacular 
6. I am not making an obfuscator, sorry
7. I will prob not add any of those, though i plan to make something will relaunch it if closed, I will not make it bsod lol. and usb spread doesnt work on anything window 8.1+
8. ill look into it thx
9. it does show it all, its most likely under the explorer process (because a lot of things are a sub process of explorer)
10. thats why there is a pause button at the top of it. but i do agree it should be improved and is quite slow, i plan to overhaul it.
11. interesting idea, that most likely wont be done in a recent update, but in the near future prob
12. ngl I think their fine, would you be able to point out whats wrong with them?
13. back up client?
14. Ill add a better warning, but the version does need to in correct format (blame windows not me)
15. I'm sorry but I am not google translating everything lol

**Comment by vv0n** [comment]
1. Add xeno rat server.exe file to tray
2. Popup or both
3. Client restoration (for changing pc or ip adress)
4. Make registry editable.
5. Is it intended for multiple xeno rat server.exe to turn on?

My mother tongue is not English, so I am not good at English.

**Comment by vv0n** [comment]
+ Is there a feature in the file manager that runs a file(in my computer) right away without uploading it? I don't remember.

**Comment by moom825** [comment]
i will keep these ideas in mind, im just gonna close it for now because it looks better
