### ISSUE TITLE
HVNC doesnt take mouse input men

### ISSUE THREAD

**Issue by BlitzFan1209** [moom825/xeno-rat#31]
fix pless

**Comment by LightYagami28** [comment]
I made a fix in my fork and then i made a pull request

**Comment by moom825** [comment]
i have not been able to recreate the issue except with the opera browser, they have some sort of anti-hvnc or something they implement interfere with it, I personally don't believe hvnc is possible on opera without dll injection (but im happy to be proven wrong), but if your problem is with opera, there are not really any plans to fix it (for now).
